//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerdePerakende.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Tel { get; set; }
        public string EMail { get; set; }
        public string Adress { get; set; }
    }
}
