//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerdePerakende.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerdePerakendeDBEntities : DbContext
    {
        public PerdePerakendeDBEntities()
            : base("name=PerdePerakendeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Perdeler> Perdeler { get; set; }
        public virtual DbSet<Satis> Satis { get; set; }
    }
}
