//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerdePerakende.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perdeler
    {
        public int PerdeID { get; set; }
        public string PerdeAdı { get; set; }
        public string M2 { get; set; }
        public string Fiyat { get; set; }
    }
}
