//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerdePerakende.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SATISID { get; set; }
        public int MÜŞTERİID { get; set; }
        public string MÜŞTERİ { get; set; }
        public string MİKTAR { get; set; }
        public string EN { get; set; }
        public string BOY { get; set; }
        public string M2 { get; set; }
        public string FİYAT { get; set; }
    }
}
